{% set name = "kubernetes" %}
{% set version = "1.9.7" %}

{% set sha256 = "8af025a1b3fcc5c3962913742ac75aa7038f7c31785bf09a669041e680a7f014" %}
{% set sha256_win64 = "5968c2b75244353ac6736420abc2de3d8c1c458efb4122319302a0b889bb2a8f" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kubernetes/{{ name }}/archive/v{{ version }}.tar.gz  # [not win]
  url: https://dl.k8s.io/v{{ version }}/{{ name }}-node-windows-amd64.tar.gz  # [win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: {{ sha256 }}  # [not win]

  fn: {{ name }}-client-{{ version }}.tar.gz  # [win]
  sha256: {{ sha256_win64 }}  # [win]

build:
  skip: True  # [win32]
  number: 0

requirements:
  build:
    - go 1.9.*  # [not win]
    - rsync  # [not win]
    - make  # [not win]
    - toolchain  # [not win]

test:
  commands:
    - cloud-controller-manager --version  # [linux]
    - hyperkube --version  # [linux]
    - kube-aggregator --help  # [linux]
    - kube-apiserver --help  # [linux]
    - kube-controller-manager --help  # [linux]
    - kube-proxy --help  # [not osx]
    - kubectl --help
    - kubelet --help  # [linux]
    
    # ugly hack because cloud-controller-manager is not a dynamic executable
    - mv $PREFIX/bin/cloud-controller-manager .  # [linux]
    - conda inspect linkages -p $PREFIX {{ name|lower }}  # [not win]
    - conda inspect objects -p $PREFIX {{ name|lower }}  # [osx]
    - mv cloud-controller-manager $PREFIX  # [linux]

about:
  home: https://www.kubernetes.io
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE  # [not win]
  license_file: LICENSES  # [win]
  summary: Production-Grade Container Orchestration
  doc_url: https://v1-9.docs.kubernetes.io/docs/home/
  dev_url: https://github.com/kubernetes/kubernetes

extra:
  recipe-maintainers:
    - sodre
