travis:
  secure:
    BINSTAR_TOKEN: H14NV1LP/vSgoBvRd8aPf0XcCXqQsC86zHqDlOgkjCxiCmztsv6DOSrXBMykFDSUHhOklM3mBcOD+jDUCaRzv1kxxOJpgBh5mmFSnhqZYRX+nJUYDVj6IBzy/fVEIZkdYiKrSEq9gKtGwjsIlw+T4ulYqyKjLSv6k1x8ioz50Kouq8Icr6zX2b/SeL5X5f4Oja+d+OeOcKCMQn/GkLRB0l1hl2ymlZh+alVNTjgr0JLTUINZftqOI7edlPrDrYLvl39m9T78jV0Dac7vvGnG2p9MFx8t9744LOxmE0MgWBgALZ39vjugbfFgQ2tz1YfnicYd7TMG+5LvTN3ap9Wt77oUvvtFaCoV3dvPGy8OFux3awCsv1KImE10okk8e+g/OGv2HfnQ6B8atb7KBsajD95A4zD4v/0SFGL9ECuUQf4QOTEsbrKsTT+gfvTmHyhfL51XT2pygQThcYDOQuJzEeYnMLdm+tz4T5CgZgwJyoudJrIrCvSLptOje+PXdWXAok1hTqPf0rnANNe7p7soJbpVy0wVDX/iOH3jzduYw/V9lmAilvfhOp5nZlryRVeSaeqKilTj7IzL8c6ZfzDKNkly/PkNvU2cckeyfxX8ka8R2WojVOtoC1cbFJm7803jbuXTQjHKuF0ls/yRlJaAbM1ZfVSzdkKnfX5AMlniJVY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
